### ISSUE TITLE
curl | sh is a bad pattern and should not be advertised

### ISSUE THREAD

**Issue by ccoenen** [freedomofpress/sunder#121]
The `README` features the suggestion to curl some script directly into a shell. At least it's not a root shell, but nevertheless this pattern is a very bad one to promote. Especially for a security tool.

(I'm referring to this section on rust: 
https://github.com/freedomofpress/sunder/blob/fbae4ac71ceddbfb86c6e9697d64884c597b0a2e/README.md#development )

**Comment by conorsch** [comment]
How about:

```
curl -q https://sh.rustup.rs -o rustup.sh && sh rustup.sh
```

@ccoenen ?

**Comment by ccoenen** [comment]
The underlying problem, that you're running unknown code remains. Checking in the browser beforehand is not sufficient. Checking afterwards is possible in this second suggestion, but then you may already have run something odd on your system.

Here's a writeup (including proof of concept) where someone delivers different things to a browser or to curl: https://www.djm.org.uk/posts/protect-yourself-from-non-obvious-dangers-curl-url-pipe-sh/

**Comment by eloquence** [comment]
Note that this is the installation method Rust itself currently advertises:

https://www.rust-lang.org/en-US/install.html

It may be appropriate to simply omit the shell command from the docs, and refer to upstream for install instructions, which may be a good idea in any case since we're otherwise committing to ensuring that this specific command (with or without modifications) keeps working. Going into detail about the pros and cons of Rust's own preferred distribution approach seems out of scope for Sunder's documentation, however. Does that sound like a reasonable resolution @ccoenen?

**Comment by ccoenen** [comment]
I'm ok with removal. Most of all, I want to prevent a "if _they_ are promoting it, it must be OK" situation. This will accomplish that end, so that's fine by me.

**Comment by conorsch** [comment]
Resolved via #123. Thanks for your input here, @ccoenen. Let us know if you have any other feedback!
