### ISSUE TITLE
During recovery, a deleted secret share cannot be reused immediately after deletion

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/sunder#97]
# Bug

## Steps to Reproduce

1. Open Sunder
2. Click **Recover It**
3. Click **Select File**, choose a saved secret share.
4. In the list of secret shares, hover over "Share #1 successfully processed" and click the **X** to delete it.
5. Click **Select File**, choose *the same* saved secret share again.

### Expected Behavior

The secret share is loaded, and a list entry labeled "Share #1 successfully processed" is displayed.

### Actual Behavior

The secret share is not loaded, and no new list entry is created.

**Comment by koenaad** [comment]
I noticed that it's not necessary to delete the share (step 4) to recreate this issue. If you add the same share twice, the second time you would expect to get the error "Duplicate share" but this does not happen.

This is probably caused by [`FileInput.js::onFileChanged`](https://github.com/freedomofpress/sunder/blob/7710190ad6e2bbf62a8f299fd0782e7e42d6a345/src/components/FileInput.js#L34) which is used to load the file. If you load the same file as last time, this function will not be called.
I would expect something needs to change on [line 86](https://github.com/freedomofpress/sunder/blob/master/src/components/FileInput.js#L86), but I'm not sure what...
